application: log-collector-dev
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /lagr/.*
  script: lagr.server.pkg_loader.app

- url: /.*
  script: lagr.server.pkg_loader.app
  login: admin

inbound_services:
- channel_presence

# vim:nospell
